### ISSUE TITLE
Extensibility through private REST API and WebHooks

### ISSUE THREAD

**Issue by louisremi** [hoodiehq/hoodie-plugin-example#3]
At Prototypo we are switching to a micro-service architecture and to Function as a Service infrastructure (experimenting both with Amazon Lambda and Google Cloud Function).
Developers in our team and around us are very comfortable extending and building on top of external services (payment gateway, CRM, etc.) through private REST APIs (the ones requiring private tokens) and WebHooks. In my opinion, this results in better security, stability, as well as simpler testing and continuous integration. I want to extend my backend and update my extensions without having to shutdown and restart my database! :-)

I recognize such extensibility might not cover all use-cases for plugins (registration-validation for example), and performances will not be ideal. But this is, in my opinion, the best way to start.

**Comment by inator** [comment]
+1 on the hot loading of plugins.  Perhaps plugin management should be handled outside of the app package and in a config db of some sort.

**Comment by inator** [comment]
See https://github.com/gr2m/milestones/issues/89#issuecomment-219223071 for reference

**Comment by gr2m** [comment]
I honestly don’t get what you would like from Hoodie? The database is separated from hoodie in production, you would use a proper CouchDB for proper scalability. You can use CouchDB as the event bus for a microservice architecture. You plan to make it possible to start plugins in separate processes which all connect to the same CouchDB. A lot of the backend logic is based on background tasks anyway, which are simple json documents that are synced between the clients and a tasks database, so that shouldn’t be too hard. 

But this is not a priority right now

**Comment by louisremi** [comment]
I have to admit my Hoodie skills are a bit rusty. I really need to give a look at the new documentation. The only logic we have left in our latest Hoodie plugin is an endpoint that checks if a username already exists, and one that answers to a Stripe WebHook by adding a Stripe customerId to a user document.
Maybe all of that is directly feasible using Hoodie's REST API.

My main interest here is in WebHooks, i.e. having an easy way to send specific Hoodie events to a specific URL.

**Comment by gr2m** [comment]
> My main interest here is in WebHooks, i.e. having an easy way to send specific Hoodie events to a specific URL.

that won’t be a problem

**Comment by gr2m** [comment]
can we close this then? Any further things you’d like to discuss?

**Comment by louisremi** [comment]
I believe it should be ok.
